name: Linter CI

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Poetry setup
        run: pip install poetry
      - name: Run flake8
        run: poetry run flake8 brain_games
        env: 
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
