name: Linter CI

on: [push]
     
jobs: 
  build:   
    runs-on: ubuntu-latest

    steps:
    - name: Pip install
      run: pip install poetry
    - name: Testing pip    
      run: make install      
      
               

      
      
