name: Linter CI

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v1.0.0
      - name: Test
        run: make lint
        env: 
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
