name: Linter CI

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          pip install poetry
          make install  
      - name: Run flake8
        run: make lint 
        
